name: example
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
homepage: https://github.com/githubuser/example#readme
dependencies:
- base >=4.7 && <5
- migrator-discover
- migrator-core
executables:
  example:
    main: Main.hs
    source-dirs: src
